config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :orders

  resources :line_items

  resources :carts

  get 'store/index'

  resources :products

  resources :line_items do
    put 'decrease', on: :member
    put 'increase', on: :member
  end

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store', via: :all
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :line_items
	before_destroy :ensure_not_referenced_by_any_line_item

	validates :title, :description, :image_url, presence: true
	validates :price, numericality: {greater_than_or_equal_to: 0.01}
	validates :title, uniqueness: true
	validates :image_url, allow_blank: true, format: {
	with: %r{\.(gif|jpg|png)\Z}i,
	message: 'Only GIF, JPG and PNG.'
	}

	def self.latest
		Product.order(:updated_at).last
	end
	
	private 
	
	def ensure_not_referenced_by_any_line_item
		if line_items.empty?
		  return true
		else
		  errors.add(:base, 'Product Position Exist')
		  return false
		end
        end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_admin_user!, except: [:show ]
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /products.json
  def index
    @products = Product.where(locale: I18n.locale)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new(permitted_params[:product])
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(permitted_params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(permitted_params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 10 %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :locale %><br>
    <%= f.select :locale, LANGUAGES, :selected => I18n.locale  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<% if user_signed_in? %>
 Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path %> |
  <%= link_to "Login", new_user_session_path %>
<% end %>

<table>
 <% @products.each do |product| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
   <td>
	<%= image_tag(product.image_url, class: 'list_image') %>
   </td>
   <td class="list_description">
	<dl>
	 <dt><%= product.title %></dt>
	 <dd><%= truncate(strip_tags(product.description),length: 80) %></dd>
         <dd><%= number_to_currency(product.price, :unit =>'€') %></dd>
	</dl>
   </td>

   <td class="list_actions">
	<%= link_to 'Show', product %><br/>
	<%= link_to 'Edit', edit_product_path(product) %><br/>
	<%= link_to 'Destroy', product, method: :delete,
		data: { confirm: 'Are you sure?' } %>
   </td>
  </tr>
 <% end %>
</table>

<br />

<%= link_to 'New product', new_product_path %>

app/views/products/index_old.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.image_url %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
  <strong></strong>
  <%= image_tag(@product.image_url) %>
</p>
<p>
  <strong><%= I18n.t('.prodname') %></strong>
  <%= @product.title %>
</p>

<p>
  <strong><%= I18n.t('proddescr') %></strong>
  <%= @product.description %>
</p>
<p>
  <strong><%= I18n.t('prodprice') %></strong>
  <%= number_to_currency(@product.price, :unit =>'AZN') %>
</p>
<% if can?  :update, @product %>
<%= link_to I18n.t('.prodedit'), edit_product_path(@product) %> |
<% end %>
<%= link_to I18n.t('.prodback'), store_path %>